#!/bin/sh
cleanup() {
    pkill hello-wayland
    exit
}

trap cleanup INT TERM

swaymsg -t subscribe -m '[ "window" ]' | while read line ; do echo -n "$line" | sway-dynamic-workspace keep-workspace ; done
